# Generated by Django 6.0.6 on 2026-06-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
