# Generated by Django 6.0.6 on 2026-06-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0003_alter_word_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='parent',
        ),
        migrations.AddField(
            model_name='word',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='lexicon.word'),
        ),
    ]
